apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wazuh-mcp.fullname" . }}-tenants
  labels:
    {{- include "wazuh-mcp.labels" . | nindent 4 }}
data:
  server.yaml: |
    {{- .Values.server.yaml | nindent 4 }}
  tenants.yaml: |
    {{- .Values.tenants.yaml | nindent 4 }}
